version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: synthform
      POSTGRES_USER: synthform
      POSTGRES_PASSWORD: synthform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "7175:7175"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://synthform:synthform@db:5432/synthform
    volumes:
      - ./apps/server:/app
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py runserver 0.0.0.0:7175"

volumes:
  postgres_data:
