services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: synthform
      POSTGRES_USER: synthform
      POSTGRES_PASSWORD: synthform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://synthform:synthform@db:5432/synthform
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./apps/server:/app
    ports:
      - "7175:7175"
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run daphne -b 0.0.0.0 -p 7175 synthform.asgi:application"

  twitch:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://synthform:synthform@db:5432/synthform
      - REDIS_URL=redis://redis:6379/0
      - DISABLE_BACKGROUND_SERVICES=true
    volumes:
      - ./apps/server:/app
    ports:
      - "4343:4343"
    command: uv run python -m shared.services.twitch.service

volumes:
  postgres_data:
  redis_data:
