# Generated by Django 5.2.5 on 2025-08-27 01:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitch_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('youtube_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('discord_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'members',
                'indexes': [models.Index(fields=['twitch_id'], name='members_twitch__000720_idx'), models.Index(fields=['created_at'], name='members_created_1df6fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('twitch', 'Twitch'), ('patreon', 'Patreon'), ('discord', 'Discord')], db_index=True, max_length=20)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.member')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source', 'event_type'], name='events_source_2f9764_idx'), models.Index(fields=['timestamp'], name='events_timesta_ba2f67_idx'), models.Index(fields=['member', 'timestamp'], name='events_member__e91ca9_idx'), models.Index(fields=['correlation_id'], name='events_correla_d00053_idx')],
            },
        ),
    ]
