# Generated by Django 5.2.5 on 2025-08-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_correla_2f9f43_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='correlation_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='legacy_correlation_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source_id',
        ),
    ]
