# Generated by Django 5.2.5 on 2025-08-27 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('discord', 'Discord')], db_index=True, default='twitch', max_length=20)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tokens',
                'indexes': [models.Index(fields=['platform', 'user_id'], name='tokens_platfor_7c18ee_idx'), models.Index(fields=['platform', 'created_at'], name='tokens_platfor_969e60_idx')],
                'unique_together': {('platform', 'user_id')},
            },
        ),
    ]
