# Generated by Django 5.2.5 on 2025-08-27 20:29

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
