# Generated by Django 5.2.5 on 2025-08-31 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_migrate_to_uuid_ids'),
    ]

    operations = [
        # The data migration already changed the database structure.
        # This just updates Django's model state to match the database reality.
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes needed
            state_operations=[
                migrations.AlterField(
                    model_name='session',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ]
        ),
    ]
