# Generated by Django 5.2.5 on 2025-09-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Stream Status', 'verbose_name_plural': 'Stream Status'},
        ),
    ]
