# Generated by Django 5.2.5 on 2025-09-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_status_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=0, help_text='Total seconds streamed in this session'),
        ),
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the stream went offline', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the stream went live', null=True),
        ),
    ]
