# Generated by Django 5.2.5 on 2025-10-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='ironmon_cha_name_503794_idx')],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('trainer', models.TextField()),
                ('order', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='checkpoints', to='ironmon.challenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seeds', to='ironmon.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='ironmon.checkpoint')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='ironmon.seed')),
            ],
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['challenge', 'order'], name='ironmon_che_challen_042a18_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['challenge'], name='ironmon_che_challen_f913f3_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['order'], name='ironmon_che_order_dce3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['challenge'], name='ironmon_see_challen_73ba33_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['seed'], name='ironmon_res_seed_id_add921_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['checkpoint'], name='ironmon_res_checkpo_5bb076_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['result'], name='ironmon_res_result_2d5370_idx'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('seed', 'checkpoint'), name='unique_seed_checkpoint'),
        ),
    ]
