# Generated by Django 5.2.5 on 2025-09-19 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_remove_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFBotPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.IntegerField(default=1)),
                ('atk', models.IntegerField(default=0)),
                ('mag', models.IntegerField(default=0)),
                ('spi', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('preferedstat', models.CharField(default='none', max_length=10)),
                ('gil', models.BigIntegerField(default=0)),
                ('collection', models.IntegerField(default=0)),
                ('ascension', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('freehirecount', models.IntegerField(default=0)),
                ('season', models.IntegerField(default=4)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('esper', models.CharField(blank=True, max_length=100)),
                ('jobap', models.IntegerField(default=0)),
                ('m1', models.CharField(blank=True, max_length=50)),
                ('m2', models.CharField(blank=True, max_length=50)),
                ('m3', models.CharField(blank=True, max_length=50)),
                ('m4', models.CharField(blank=True, max_length=50)),
                ('m5', models.CharField(blank=True, max_length=50)),
                ('m6', models.CharField(blank=True, max_length=50)),
                ('m7', models.CharField(blank=True, max_length=50)),
                ('job_atk', models.IntegerField(default=0)),
                ('job_mag', models.IntegerField(default=0)),
                ('job_spi', models.IntegerField(default=0)),
                ('job_hp', models.IntegerField(default=0)),
                ('card', models.CharField(blank=True, max_length=100)),
                ('card_collection', models.IntegerField(default=0)),
                ('card_passive', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ffbot_stats', to='events.member')),
            ],
            options={
                'verbose_name': 'FFBot Player Stats',
                'verbose_name_plural': 'FFBot Player Stats',
                'db_table': 'games_ffbot_playerstats',
                'indexes': [models.Index(fields=['member'], name='games_ffbot_member__1b636e_idx')],
            },
        ),
    ]
