# Generated by Django 5.2.5 on 2024-09-19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbot', '0001_initial'),
    ]

    operations = [
        # Rename the model
        migrations.RenameModel(
            old_name='FFBotPlayerStats',
            new_name='Player',
        ),
        # Remove the old id field
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        # Add UUID as primary key
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        # Update the related name
        migrations.AlterField(
            model_name='player',
            name='member',
            field=models.OneToOneField(
                on_delete=models.deletion.CASCADE,
                related_name='ffbot_player',
                to='events.member'
            ),
        ),
    ]