# Generated by Django 5.2.5 on 2025-09-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffbot', '0003_add_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'FFBot Player', 'verbose_name_plural': 'FFBot Players'},
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='ffbot_playe_member__cb428e_idx',
            old_name='games_ffbot_member__1b636e_idx',
        ),
        migrations.AlterModelTable(
            name='player',
            table=None,
        ),
    ]
