# Generated by Django 5.2.5 on 2025-09-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_migrate_tokens_from_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='token',
            new_name='authenticat_service_e48650_idx',
            old_name='authenticat_service_4e4f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='token',
            new_name='authenticat_last_re_3d203b_idx',
            old_name='authenticat_last_re_7b8e5c_idx',
        ),
    ]
