# Generated by Django 5.2.5 on 2025-08-27 23:20

import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('confidence', models.FloatField(blank=True, help_text='Transcription confidence score', null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_stream_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='streams.session')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='transcripti_timesta_d1663a_idx'), models.Index(fields=['confidence'], name='transcripti_confide_d86560_idx'), models.Index(fields=['correlation_id'], name='transcripti_correla_8bacb4_idx')],
            },
        ),
    ]
