# Generated by Django 5.2.5 on 2025-09-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='legacy_stream_session_id',
        ),
    ]
