# Generated by Django 5.2.5 on 2025-08-28 21:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timeout_started_at', models.DateTimeField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(default=48000)),
                ('channels', models.IntegerField(default=2)),
                ('bit_depth', models.IntegerField(default=16)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('source_id', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=200)),
                ('data_size', models.IntegerField()),
                ('sample_rate', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('bit_depth', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='audio.session')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='audio_chunk_session_106478_idx'), models.Index(fields=['processed'], name='audio_chunk_process_b73abf_idx')],
            },
        ),
    ]
