# Generated by Django 5.2.5 on 2025-09-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_session_unique_active_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
