# Generated by Django 5.2.5 on 2025-09-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_delete_chunk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
