# Generated by Django 5.2.5 on 2025-10-23 15:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_remove_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('text', models.TextField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('quotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_said', to='events.member')),
                ('quoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_recorded', to='events.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quotee', 'year'], name='quotes_quot_quotee__e05290_idx'), models.Index(fields=['year'], name='quotes_quot_year_c7d22e_idx'), models.Index(fields=['created_at'], name='quotes_quot_created_ede808_idx')],
            },
        ),
    ]
