/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OmnibarRouteImport } from './routes/omnibar'
import { Route as MusicRouteImport } from './routes/music'
import { Route as LimitbreakRouteImport } from './routes/limitbreak'
import { Route as CoworkingRouteImport } from './routes/coworking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugEventsRouteImport } from './routes/debug/events'
import { Route as fullStartRouteImport } from './routes/(full)/start'

const OmnibarRoute = OmnibarRouteImport.update({
  id: '/omnibar',
  path: '/omnibar',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitbreakRoute = LimitbreakRouteImport.update({
  id: '/limitbreak',
  path: '/limitbreak',
  getParentRoute: () => rootRouteImport,
} as any)
const CoworkingRoute = CoworkingRouteImport.update({
  id: '/coworking',
  path: '/coworking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEventsRoute = DebugEventsRouteImport.update({
  id: '/debug/events',
  path: '/debug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const fullStartRoute = fullStartRouteImport.update({
  id: '/(full)/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coworking': typeof CoworkingRoute
  '/limitbreak': typeof LimitbreakRoute
  '/music': typeof MusicRoute
  '/omnibar': typeof OmnibarRoute
  '/start': typeof fullStartRoute
  '/debug/events': typeof DebugEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coworking': typeof CoworkingRoute
  '/limitbreak': typeof LimitbreakRoute
  '/music': typeof MusicRoute
  '/omnibar': typeof OmnibarRoute
  '/start': typeof fullStartRoute
  '/debug/events': typeof DebugEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coworking': typeof CoworkingRoute
  '/limitbreak': typeof LimitbreakRoute
  '/music': typeof MusicRoute
  '/omnibar': typeof OmnibarRoute
  '/(full)/start': typeof fullStartRoute
  '/debug/events': typeof DebugEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coworking'
    | '/limitbreak'
    | '/music'
    | '/omnibar'
    | '/start'
    | '/debug/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coworking'
    | '/limitbreak'
    | '/music'
    | '/omnibar'
    | '/start'
    | '/debug/events'
  id:
    | '__root__'
    | '/'
    | '/coworking'
    | '/limitbreak'
    | '/music'
    | '/omnibar'
    | '/(full)/start'
    | '/debug/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoworkingRoute: typeof CoworkingRoute
  LimitbreakRoute: typeof LimitbreakRoute
  MusicRoute: typeof MusicRoute
  OmnibarRoute: typeof OmnibarRoute
  fullStartRoute: typeof fullStartRoute
  DebugEventsRoute: typeof DebugEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/omnibar': {
      id: '/omnibar'
      path: '/omnibar'
      fullPath: '/omnibar'
      preLoaderRoute: typeof OmnibarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limitbreak': {
      id: '/limitbreak'
      path: '/limitbreak'
      fullPath: '/limitbreak'
      preLoaderRoute: typeof LimitbreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coworking': {
      id: '/coworking'
      path: '/coworking'
      fullPath: '/coworking'
      preLoaderRoute: typeof CoworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/events': {
      id: '/debug/events'
      path: '/debug/events'
      fullPath: '/debug/events'
      preLoaderRoute: typeof DebugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(full)/start': {
      id: '/(full)/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof fullStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoworkingRoute: CoworkingRoute,
  LimitbreakRoute: LimitbreakRoute,
  MusicRoute: MusicRoute,
  OmnibarRoute: OmnibarRoute,
  fullStartRoute: fullStartRoute,
  DebugEventsRoute: DebugEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
