/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OmnibarRouteImport } from './routes/omnibar'
import { Route as IndexRouteImport } from './routes/index'

const OmnibarRoute = OmnibarRouteImport.update({
  id: '/omnibar',
  path: '/omnibar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/omnibar': typeof OmnibarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/omnibar': typeof OmnibarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/omnibar': typeof OmnibarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/omnibar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/omnibar'
  id: '__root__' | '/' | '/omnibar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OmnibarRoute: typeof OmnibarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/omnibar': {
      id: '/omnibar'
      path: '/omnibar'
      fullPath: '/omnibar'
      preLoaderRoute: typeof OmnibarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OmnibarRoute: OmnibarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
