name: Deploy to OrbStack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - name: Deploy containers
      run: |
        docker compose -f docker-compose.prod.yml up --build --force-recreate -d --remove-orphans

    - name: Clean up old Docker images
      run: |
        docker image prune -f
