# Generated by Django 5.2.5 on 2025-09-12 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('timer_mode', models.BooleanField(default=False)),
                ('timer_initial_seconds', models.IntegerField(default=3600)),
                ('seconds_per_sub', models.IntegerField(default=180)),
                ('seconds_per_tier2', models.IntegerField(default=360)),
                ('seconds_per_tier3', models.IntegerField(default=900)),
                ('max_timer_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_subs', models.IntegerField(default=0)),
                ('total_resubs', models.IntegerField(default=0)),
                ('total_bits', models.IntegerField(default=0)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timer_seconds_remaining', models.IntegerField(default=0)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_paused_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='campaigns.campaign')),
            ],
            options={
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threshold', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_unlocked', models.BooleanField(db_index=True, default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('announcement_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['threshold'],
                'unique_together': {('campaign', 'threshold')},
            },
        ),
    ]
