# Generated by Django 5.2.5 on 2025-09-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='announcement_text',
        ),
    ]
