# Generated by Django 5.2.5 on 2025-09-25 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_announcement_text'),
        ('events', '0003_remove_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier1_count', models.IntegerField(default=0)),
                ('tier2_count', models.IntegerField(default=0)),
                ('tier3_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('first_gift_at', models.DateTimeField(blank=True, null=True)),
                ('last_gift_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='campaigns.campaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_gifts', to='events.member')),
            ],
            options={
                'ordering': ['-total_count'],
                'indexes': [models.Index(fields=['campaign', '-total_count'], name='campaigns_g_campaig_41c902_idx'), models.Index(fields=['member', 'campaign'], name='campaigns_g_member__6b3761_idx')],
                'unique_together': {('member', 'campaign')},
            },
        ),
    ]
